#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

#window
yabai -m config window_topmost off
yabai -m config window_placement second_child
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.8
yabai -m config window_shadow off
yabai -m config window_border off
yabai -m config window_border_width 1
yabai -m config active_window_border_color 0xffffffff
yabai -m config normal_window_border_color 0xff505050
yabai -m config insert_window_border_color 0xffd75f5f

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10
# New window spawns to the left if vertical split, or top if horizontal split
yabai -m config window_placement first_child

# ignore app
yabai -m rule --add app="^系统设置$" manage=off
yabai -m rule --add app="^提醒事项$" manage=off
yabai -m rule --add app="^关于本机$" manage=off
yabai -m rule --add app="^访达$" manage=off
yabai -m rule --add app="^1password$" manage=off
yabai -m rule --add app="*setapp" manage=off
yabai -m rule --add app="*Setapp" manage=off
yabai -m rule --add app="*istat" manage=off
yabai -m rule --add app="*iStat" manage=off
yabai -m rule --add app="海星云" manage=off
yabai -m rule --add app="Clean*" manage=off
yabai -m rule --add app="svelte*" manage=off

# force the app in the specify space
yabai -m rule --add app="^微信$" space=1

yabai -m config window_animation_duration 0
echo "yabai configuration loaded.."s
