#!/usr/bin/env sh
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_shadow off \
	window_animation_duration 10.0 \
	window_animation_frame_rate 120 \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity off \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 8 \
	bottom_padding 8 \
	left_padding 8 \
	right_padding 8 \
	window_gap 3 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

# ignore app
yabai -m rule --add app="^系统设置$" manage=off
yabai -m rule --add app="^提醒事项$" manage=off
yabai -m rule --add app="^关于本机$" manage=off
yabai -m rule --add app="^1password$" manage=off
yabai -m rule --add app="*setapp" manage=off
yabai -m rule --add app="*Setapp" manage=off
yabai -m rule --add app="*istat" manage=off
yabai -m rule --add app="*iStat" manage=off
yabai -m rule --add app="海星云" manage=off
yabai -m rule --add app="Clean*" manage=off
yabai -m rule --add app="svelte*" manage=off

# force the app in the specify space
# yabai -m rule --add app="^微信$" space=1
echo "yabai configuration loaded.."s
